probabilitas ={
    "Gajah": 0,
    "Kuda": 0,  
    "Kucing": 0,
    "Kanguru": 0,
    "Sapi": 0,
    "Penguin": 0,
    "Ular": 0,
    "Buaya": 0,
    "Monyet": 0,
    "Komodo": 0,
    "Rusa": 0,
    "Banteng": 0,
    "Kelinci": 0,
    "Beruang": 0,
    "Anjing": 0,
    "Katak": 0,
    "Kupu-kupu": 0,
    "Laba-laba": 0,
    "Babi": 0,
    "Ayam": 0,
    "Orang hutan": 0,
    "Jerapah": 0,
    "Singa": 0,
    "Harimau": 0,
    "Cheetah": 0
}